// <auto-generated />
namespace MobiObmen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202108130908381_addrequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
